version: '3.7'

volumes:
  mysql_data:
    driver: local
  rabbit_data:
    driver: local
  minio_data1:
    driver: local

services:
  rabbitmq:
    container_name: hasty_rabbitmq
    image: rabbitmq:3.7-management-alpine
    volumes:
      #- "/usr/local/dev/rabbitmq:/var/lib/rabbitmq/mnesia"
      - rabbit_data:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        report:
            aliases:
                - net-rabbitmq
  
  mysql:
    container_name: hasty_mysql
    image: mysql:5.7.25
    volumes:
      # - "/usr/local/dev/mysql:/var/lib/mysql"
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "hasty_database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
        report:
            aliases:
                - net-mysql
    # healthcheck:
    #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #     timeout: 20s
    #     retries: 10

  # minio1:
  #   container_name: hasty_minio1
  #   image: minio/minio:RELEASE.2019-08-21T19-40-07Z
  #   volumes:
  #     - minio_data1:/data
  #   ports:
  #     - "9001:9000"
  #   environment:
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio123
  #     PUBLIC_URL: http://public.examplemin.io:9001
  #   command: server /data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
  #     interval: 1m30s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 3m
  #   networks:
  #       report:
  #           aliases:
  #               - net-minio

  # Django web
  backend:
    build:
      context: .
      dockerfile: "./application/Dockerfile"
    command: sh start_backend.sh
    container_name: hasty_backend
    volumes:
      - "./application/:/image_service"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: 'hasty_database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ""
    ports:
      - "8000:8000"
    links:
      - mysql
      - rabbitmq
      # - minio1
    depends_on:
      - mysql
      - rabbitmq
      # - minio1
    networks:
        report:
            aliases:
              - net-service

networks:
  report:
    driver: bridge

