# Generated by Django 2.1.7 on 2019-08-26 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Token')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Create Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Token')),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('xDimension', models.IntegerField(blank=True, null=True)),
                ('yDimension', models.IntegerField(blank=True, null=True)),
                ('orientation', models.IntegerField(blank=True, null=True)),
                ('software', models.CharField(blank=True, max_length=50, null=True)),
                ('flash', models.CharField(blank=True, max_length=150, null=True)),
                ('metering_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('saturation', models.CharField(blank=True, max_length=50, null=True)),
                ('sharpness', models.CharField(blank=True, max_length=50, null=True)),
                ('contrast', models.CharField(blank=True, max_length=50, null=True)),
                ('x_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('y_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('aperture_value', models.CharField(blank=True, max_length=50, null=True)),
                ('focal_length', models.CharField(blank=True, max_length=50, null=True)),
                ('exif_version', models.CharField(blank=True, max_length=50, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='gallery.Gallery', verbose_name='Gallery')),
            ],
        ),
    ]
