# Generated by Django 2.1.7 on 2019-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='image',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True, verbose_name='Token'),
        ),
    ]
